// critRecord.js — assemble the structured crit record + render a Markdown
// summary. UMD: Node (relay, tests) + browser. This is M4: a finished crit's
// portable, exportable output. The JSON record is the interchange object every
// sink (Figma, Jira, …) reads; the Markdown is the human-readable share.
//
// ActionItem shape aligns with docs/data-model.md:
//   { id, content, type, scope[], targets[], transcriptAnchor{t,speaker}, rubricTag, status }

"use strict";

const ACTIONABLE = new Set(["suggestion", "concern", "decision"]);

// Heuristic action-item extraction (offline fallback). The LLM extractor in
// llmProvider produces better, merged items; this keeps export working with no key.
function extractActionItemsHeuristic(utterances) {
  const items = [];
  utterances.forEach((u, i) => {
    if (!ACTIONABLE.has(u.classification)) return;
    items.push({
      id: "ai-" + String(i + 1).padStart(3, "0"),
      content: u.text,
      type: u.classification,
      scope: ["design-level"],
      targets: [],
      transcriptAnchor: { t: u.t || "", speaker: u.speaker || "" },
      rubricTag: u.rubricTag || (u.trigger ? u.trigger : null),
      status: "open"
    });
  });
  return items;
}

// Assemble the record from a finished session. actionItems may be provided
// (e.g. from the LLM extractor); otherwise the heuristic runs.
function buildRecord(session) {
  const utterances = (session.utterances || []).map((u) => ({
    speaker: u.speaker, t: u.t, text: u.text, classification: u.classification || null
  }));
  const speakers = [...new Set(utterances.map((u) => u.speaker).filter(Boolean))];
  const actionItems = session.actionItems || extractActionItemsHeuristic(session.utterances || []);
  return {
    critbotVersion: "0.4",
    meta: {
      title: (session.meta && session.meta.title) || "Critique",
      library: (session.meta && session.meta.library) || null,
      source: (session.meta && session.meta.source) || "live",
      startedAt: (session.meta && session.meta.startedAt) || null,
      endedAt: (session.meta && session.meta.endedAt) || new Date().toISOString(),
      invited: (session.meta && session.meta.invited) || [], // M6: calendar attendees (M7 roster seam)
      speakers                                               // who actually spoke (from diarization)
    },
    scorecard: session.scorecard || [],
    coaching: session.coaching || [],
    transcript: utterances,
    actionItems
  };
}

function toMarkdown(record) {
  const m = record.meta || {};
  const L = [];
  L.push("# " + (m.title || "Critique"));
  L.push("");
  L.push(`*Lens: ${m.library || "—"} · ${m.endedAt || ""}*`);
  if ((m.invited || []).length) L.push(`*Invited: ${m.invited.join(", ")}*`);
  L.push(`*Spoke: ${(m.speakers || []).join(", ") || "—"}*`);
  L.push("");

  L.push("## Critique quality");
  if ((record.scorecard || []).length) {
    record.scorecard.forEach((s) => L.push(`- ${s.met ? "✅" : "⬜️"} **${s.label}** — ${s.note || ""}`));
  } else L.push("_No scorecard._");
  L.push("");

  L.push("## Action items");
  if ((record.actionItems || []).length) {
    record.actionItems.forEach((a) => {
      const tag = a.rubricTag ? ` _(${a.rubricTag})_` : "";
      const anchor = a.transcriptAnchor && a.transcriptAnchor.t ? ` — ${a.transcriptAnchor.speaker} @ ${a.transcriptAnchor.t}` : "";
      let role = ""; // M7 provenance, when a roster/policy was applied
      if (a.provenance && a.provenance.relationship && a.provenance.relationship !== "unknown") {
        role = ` ⟦${a.provenance.role || a.provenance.relationship}` + (a.weight != null ? `, weight ×${a.weight}` : "") +
          (a.promotedToDecision ? ", decision" : "") + ((a.flags || []).indexOf("junior-point-protect") !== -1 ? ", protect" : "") + `⟧`;
      }
      L.push(`- [ ] **${a.type}**: ${a.content}${tag}${anchor}${role}`);
    });
  } else L.push("_No action items extracted._");
  L.push("");

  if (record.relationshipSummary) {
    L.push("## Relationship notes");
    L.push(record.relationshipSummary.note);
    L.push("");
  }

  if ((record.coaching || []).length) {
    L.push("## Coaching notes");
    record.coaching.forEach((c) => L.push(`- _(${c.kind || "note"})_ ${c.nudge}${c.count > 1 ? ` ×${c.count}` : ""}`));
    L.push("");
  }

  L.push("## Transcript");
  (record.transcript || []).forEach((u) => {
    const cls = u.classification ? ` _[${u.classification}]_` : "";
    L.push(`- **${u.speaker}** (${u.t})${cls}: ${u.text}`);
  });
  L.push("");
  L.push("---");
  L.push("_Generated by Critbot " + (record.critbotVersion || "") + ". All demo data synthetic unless a live crit._");
  return L.join("\n");
}

const api = { buildRecord, toMarkdown, extractActionItemsHeuristic };
if (typeof module !== "undefined" && module.exports) module.exports = api;
if (typeof window !== "undefined") window.CritbotRecord = api;
